--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pod-info-test
  namespace: deployment 
  labels: 
    name: info-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info-pod
  template: 
    metadata:
      labels: 
        app: info-pod 
    spec: 
     containers:
     - name: pod-info-container
       image: kimschles/pod-info-app:latest
       ports:
       - containerPort: 3000
       env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP       

