apiVersion: apps/v1
kind: Deployment 
metadata:
  name: fe-rhrs 
  labels: 
    app: fe-rhrs 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: fe-rhrs 
  template: 
    metadata: 
      labels: 
        app: fe-rhrs 
    spec: 
      containers: 
      - name: frontend
        image: frontend
        ports: 
        - containerPort: 8080