apiVersion: v1
kind: Service
metadata:
  name: rhs-frontend-service
spec:
  selector:
    app: irhrs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: be-irhrs-backend
spec: 
  selector:
    app: irhrs-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
--- 
apiVersion: v1 
kind: pod 
metadata:
  name: irhrs-qcluster-service 
spec:
  selector: 
    app: irhrs-qcluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      

    
