apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deploymet
  labels:   
    app: nginx
spec:
  replicas: 2
  selector: 
    matchLables: 
      aap: nginx
    template: 
      metadata:
          labels:   
            app: nginx 
      spec:
        containers:
        - name: nginx 
          image: nginx:latest 
        ports:
        - containerPort: 80