# Generated by Django 4.2.16 on 2024-11-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='id',
        ),
        migrations.AddField(
            model_name='core',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='core',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='core',
            name='firstname',
            field=models.CharField(db_comment='This is your first name', max_length=200),
        ),
        migrations.AlterField(
            model_name='core',
            name='lastname',
            field=models.CharField(db_comment='This is your first name', max_length=200),
        ),
    ]
