# Generated by Django 4.2.16 on 2024-11-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_core_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('Phone_number', models.IntegerField()),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.core')),
            ],
        ),
    ]
