# Generated by Django 4.2.16 on 2024-11-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
