apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
     env: demo
spec:
   replicas: 2
   selector:
     matchLabels:
      env: demo
   template:
    metadata:
     labels:
      env: demo
    spec:
     containers:
     - name: nginx
       image: nginx

