---
- name: package installer
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name : execute a script  file

      script: /home/bimal/linuxscripts/test1.sh


    - name: messgae
      debug:
       msg: " Sucessfully executed"
